from datetime import datetime
from typing import Optional, Any

class Event:
    """
    Base Event class.
    """
    def __init__(self, type: str):
        self.type = type
        self.timestamp = datetime.utcnow()

class TickEvent(Event):
    """
    Triggered by Market Data Stream or Timer.
    """
    def __init__(self, ticker: str, price: float, timestamp: datetime):
        super().__init__("TICK")
        self.ticker = ticker
        self.price = price
        self.timestamp = timestamp

class SignalEvent(Event):
    """
    Generated by Strategy logic.
    """
    def __init__(self, ticker: str, signal_type: str, price: float, atr: float, strategy: str, confidence: float = 0.0):
        super().__init__("SIGNAL")
        self.ticker = ticker
        self.signal_type = signal_type # "BUY" / "SELL"
        self.price = price
        self.atr = atr
        self.strategy = strategy
        self.confidence = confidence

class OrderEvent(Event):
    """
    Request to place an order (Post-Risk Check).
    """
    def __init__(self, ticker: str, side: str, quantity: int, order_type: str = "MARKET"):
        super().__init__("ORDER")
        self.ticker = ticker
        self.side = side
        self.quantity = quantity
        self.order_type = order_type

class FillEvent(Event):
    """
    Simulates or captures a Trade Fill.
    """
    def __init__(self, fill_data: Any):
        super().__init__("FILL")
        self.fill = fill_data
